export const ErrorCodes = {
  // 이메일 인증 관련
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  DAILY_LIMIT_EXCEEDED: 'DAILY_LIMIT_EXCEEDED',
  INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
  VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
  VERIFICATION_NOT_FOUND: 'VERIFICATION_NOT_FOUND',
} as const;
